# Unified Hesai outdoor config for VoxelMap++
common:
  lid_topic: "/lidar_points"
  imu_topic: "/fvs/imu_raw"

preprocess:
  lidar_type: 4                # HESAIxt32 (x,y,z,intensity,timestamp,ring)
  scan_line: 128
  blind: 1
  point_filter_num: 1
  calib_laser: false

mapping:
  down_sample_size: 1.0
  max_iteration: 3
  voxel_size: 2.0
  plannar_threshold: 0.01
  max_points_size: 300
  update_size_threshold: 5
  sigma_num: 3

noise_model:
  ranging_cov: 0.04
  angle_cov: 0.1
  acc_cov_scale: 1.0
  gyr_cov_scale: 0.5

imu:
  imu_en: true
  extrinsic_T: [0.022846, -0.005619,  0.08427 ]
  extrinsic_R: [-0.012887,  0.693026,  0.720798,
                 -0.999874,  -0.015618,  -0.00286,
                 0.009275,  -0.720744,  0.69314]

visualization:
  pub_voxel_map: false
  pub_voxel_map_period: 50
  pub_point_cloud: true
  dense_map_enable: true
  pub_point_cloud_skip: false

Result:
  write_kitti_log: false
  result_path: "/tmp/voxel_map_plus_kitti.txt"
